const express = require('express');
const router = express.Router();
const adminController = require('../app/controllers/AdminController');
const authController = require('../app/controllers/AuthController');
const { verifySignUp } = require("../app/middlewares/verifySignUp");

router.put('/quan-ly-tour/:id', adminController.updateTour);
router.put('/quan-ly-tin-tuc/:id', adminController.updateTinTuc);
router.put('/quan-ly-am-thuc/:id', adminController.updateAmThuc);
router.put('/quan-ly-dia-diem/:id', adminController.updateDiaDiem);
router.put('/danh-sach-admin/:id', adminController.updateAdmin);
router.delete('/quan-ly-tour/:id', adminController.deleteTour);
router.delete('/quan-ly-tin-tuc/:id', adminController.deleteTinTuc);
router.delete('/quan-ly-am-thuc/:id', adminController.deleteAmThuc);
router.delete('/quan-ly-dia-diem/:id', adminController.deleteDiaDiem);
router.delete('/danh-sach-admin/:id', adminController.deleteAdmin);
router.get('/signup', adminController.get_signup);
router.get('/login', adminController.get_login);
router.get('/logout', adminController.logout);
router.get('/quan-ly-tour/:id/sua-tour', adminController.editTour);
router.get('/quan-ly-tour', adminController.ql_tour);
router.get('/quan-ly-tin-tuc/:id/sua-tin-tuc', adminController.editTinTuc);
router.get('/quan-ly-tin-tuc', adminController.ql_tintuc);
router.get('/quan-ly-dia-diem/:id/sua-dia-diem', adminController.editDiaDiem);
router.get('/quan-ly-dia-diem', adminController.ql_diadiem);
router.get('/quan-ly-am-thuc/:id/sua-am-thuc', adminController.editAmThuc);
router.get('/quan-ly-am-thuc', adminController.ql_amthuc);
router.get('/quan-ly-am-thuc/:id/sua-am-thuc', adminController.editAdmin);
router.get('/danh-sach-admin', adminController.ds_admin);
router.post('/quan-ly-tin-tuc', adminController.addTour);
router.post('/quan-ly-tin-tuc', adminController.addTinTuc);
router.post('/quan-ly-dia-diem', adminController.addDiaDiem);
router.post('/quan-ly-am-thuc', adminController.addAmThuc);
router.post('/signup', adminController.signup);
router.post('/', adminController.login);
router.get('/', adminController.index);

module.exports = router;